// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzURzt3JGGbNrJXFKmFbxHm19i297ue-U',
    appId: '1:998067001299:web:c5cf27f845194732d7c126',
    messagingSenderId: '998067001299',
    projectId: 'lenoy-lifesync',
    authDomain: 'lenoy-lifesync.firebaseapp.com',
    storageBucket: 'lenoy-lifesync.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRO7lYxuynbmHKi5kg31DTZSUQImnunLw',
    appId: '1:998067001299:android:845aabeced7912f4d7c126',
    messagingSenderId: '998067001299',
    projectId: 'lenoy-lifesync',
    storageBucket: 'lenoy-lifesync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1qHgcz1fLlMpyIVVlqw44B8HPTxX-FoU',
    appId: '1:998067001299:ios:be14a449f9a6ef8dd7c126',
    messagingSenderId: '998067001299',
    projectId: 'lenoy-lifesync',
    storageBucket: 'lenoy-lifesync.firebasestorage.app',
    iosBundleId: 'com.example.lifesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1qHgcz1fLlMpyIVVlqw44B8HPTxX-FoU',
    appId: '1:998067001299:ios:be14a449f9a6ef8dd7c126',
    messagingSenderId: '998067001299',
    projectId: 'lenoy-lifesync',
    storageBucket: 'lenoy-lifesync.firebasestorage.app',
    iosBundleId: 'com.example.lifesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzURzt3JGGbNrJXFKmFbxHm19i297ue-U',
    appId: '1:998067001299:web:67ae89e4b9f376a8d7c126',
    messagingSenderId: '998067001299',
    projectId: 'lenoy-lifesync',
    authDomain: 'lenoy-lifesync.firebaseapp.com',
    storageBucket: 'lenoy-lifesync.firebasestorage.app',
  );
}
